## 1. **Import libary**

In [1]:
import pyodbc
import pandas as pd
from sqlalchemy import create_engine
import urllib

In [2]:
pyodbc.drivers()

['SQL Server',
 'ODBC Driver 17 for SQL Server',
 'Microsoft Access Driver (*.mdb, *.accdb)',
 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)',
 'Microsoft Access Text Driver (*.txt, *.csv)',
 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [3]:
SERVER = 'LENOVO\SQLEXPRESS'
DATABASE = 'test'
DRIVER = 'ODBC Driver 17 for SQL Server'

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\NGUYEN\AppData\Local\Temp\ipykernel_22588\3922767854.py:1: SyntaxWarning: invalid escape sequence '\S'
  SERVER = 'LENOVO\SQLEXPRESS'

In [4]:
# 1. Cấu hình chuỗi kết nối
# Chúng ta cần quote lại chuỗi kết nối để xử lý các ký tự đặc biệt như dấu gạch chéo ngược (\)
params = urllib.parse.quote_plus(
    f'DRIVER={{{DRIVER}}};'
    f'SERVER={SERVER};'
    f'DATABASE={DATABASE};'
    f'Trusted_Connection=yes;'
)

# 2. Khởi tạo Engine
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

### 1.1. Data Stage

### 1.2. Save data stage

### 1.3. Save data dim order

In [5]:
data_dim_order = pd.read_sql("SELECT * FROM dim_order", engine)

In [6]:
data_dim_order.head(10)

   order_id  primary_product_id  is_repeat_session
0         1                   1                  0
1         2                   1                  0
2         3                   1                  0
3         4                   1                  0
4         5                   1                  0
5         6                   1                  0
6         7                   1                  0
7         8                   1                  0
8         9                   1                  0
9        10                   1                  0

In [7]:
data_dim_order.shape

(32313, 3)

In [8]:
data_dim_order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   primary_product_id  32313 non-null  int64
 2   is_repeat_session   32313 non-null  int64
dtypes: int64(3)
memory usage: 757.5 KB

In [9]:
data_dim_order.isnull().sum()

order_id              0
primary_product_id    0
is_repeat_session     0
dtype: int64

In [10]:
data_dim_order.duplicated().sum()

0

In [11]:
# save data_dim_order to csv
data_dim_order.to_csv('data/processed/dim_order.csv', index=False)

### 1.4. Save data dim papeview

In [12]:
data_dim_papeview = pd.read_sql("select * from dim_papeview", engine)

In [13]:
data_dim_papeview.head(10)

   website_pageview_id               pageview_url
0                   30                      /home
1                   32                  /products
2                   33     /the-original-mr-fuzzy
3                   34                      /cart
4                   35                  /shipping
5                   36                   /billing
6                   37  /thank-you-for-your-order
7                  178                      /home
8                  179                  /products
9                  180     /the-original-mr-fuzzy

In [14]:
data_dim_papeview.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226191 entries, 0 to 226190
Data columns (total 2 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   website_pageview_id  226191 non-null  int64
 1   pageview_url         226191 non-null  object
dtypes: int64(1), object(1)
memory usage: 3.5+ MB

In [15]:
data_dim_papeview.isnull().sum()

website_pageview_id    0
pageview_url           0
dtype: int64

In [16]:
data_dim_papeview.duplicated().sum()

0

In [17]:
data_dim_papeview.to_csv('data/processed/dim_papeview.csv', index=False)
print("Save data_dim_papeview to CSV successfully!")

Save data_dim_papeview to CSV successfully!

### 1.5. Save data dim product

In [18]:
data_dim_product = pd.read_sql("select * from dim_product", engine)

In [19]:
data_dim_product.head(10)

   product_id                product_name
0           1      The Original Mr. Fuzzy
1           2       The Forever Love Bear
2           3    The Birthday Sugar Panda
3           4  The Hudson River Mini bear

In [20]:
data_dim_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    4 non-null      int64
 1   product_name  4 non-null      object
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [21]:
data_dim_product.to_csv('data/processed/dim_product.csv', index=False)
print("Save data_dim_product to CSV successfully!")

Save data_dim_product to CSV successfully!

### 1.6. Save data dim session

In [22]:
data_dim_session = pd.read_sql("select * from dim_session", engine)

In [23]:
data_dim_session.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   website_session_id  32313 non-null  int64
 1   user_id             32313 non-null  int64
 2   utm_source          32313 non-null  object
 3   utm_campaign        32313 non-null  object
 4   utm_content         32313 non-null  object
 5   device_type         32313 non-null  object
 6   http_referer        32313 non-null  object
dtypes: int64(2), object(5)
memory usage: 1.7+ MB

In [24]:
data_dim_session.isnull().sum()

website_session_id    0
user_id               0
utm_source            0
utm_campaign          0
utm_content           0
device_type           0
http_referer          0
dtype: int64

In [25]:
data_dim_session.duplicated().sum()

0

In [26]:
data_dim_session.to_csv('data/processed/dim_session.csv', index=False)
print("Save data_dim_session to CSV successfully!")

Save data_dim_session to CSV successfully!

### 1.7. Save dat dim time table

In [27]:
data_dim_time = pd.read_sql("select * from dim_time", engine)

In [28]:
data_dim_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225504 entries, 0 to 225503
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   created_at  225504 non-null  datetime64[ns]
 1   year        225504 non-null  int64
 2   month       225504 non-null  int64
 3   day         225504 non-null  int64
 4   quater      225504 non-null  int64
 5   hour        225504 non-null  int64
 6   time_id     225504 non-null  int64
dtypes: datetime64[ns](1), int64(6)
memory usage: 12.0 MB

In [29]:
data_dim_time.isnull().sum()

created_at    0
year          0
month         0
day           0
quater        0
hour          0
time_id       0
dtype: int64

In [30]:
data_dim_time.duplicated().sum()

0

In [31]:
data_dim_time.to_csv('data/processed/dim_time.csv', index=False)
print("Save data_dim_time to CSV successfully!")

Save data_dim_time to CSV successfully!

### 1.8. Save data fact table

In [32]:
data_fact = pd.read_sql("select * from fact", engine)

In [33]:
data_fact.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280175 entries, 0 to 280174
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   website_pageview_id  280175 non-null  int64
 1   website_session_id   280175 non-null  int64
 2   order_id             280175 non-null  int64
 3   items_purchased      280175 non-null  int64
 4   price_usd            280175 non-null  float64
 5   cogs_usd             280175 non-null  float64
 6   order_item_id        280175 non-null  int64
 7   product_id           280175 non-null  int64
 8   is_primary_item      280175 non-null  int64
 9   time_id              280175 non-null  int64
 10  row_id               280175 non-null  int64
dtypes: float64(2), int64(9)
memory usage: 23.5 MB

In [34]:
data_fact.to_csv('data/processed/fact.csv', index=False)
print("Save data_fact to CSV successfully!")

Save data_fact to CSV successfully!