## 1. **Import libary**

In [1]:
import pyodbc
import pandas as pd
from sqlalchemy import create_engine
import urllib

In [2]:
pyodbc.drivers()

['SQL Server',
 'ODBC Driver 17 for SQL Server',
 'Microsoft Access Driver (*.mdb, *.accdb)',
 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)',
 'Microsoft Access Text Driver (*.txt, *.csv)',
 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [3]:
SERVER = 'LENOVO\SQLEXPRESS'
DATABASE = 'toy_store_datawarehouse'
DRIVER = 'ODBC Driver 17 for SQL Server'

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\NGUYEN\AppData\Local\Temp\ipykernel_7752\1389477876.py:1: SyntaxWarning: invalid escape sequence '\S'
  SERVER = 'LENOVO\SQLEXPRESS'

In [4]:
# 1. Cấu hình chuỗi kết nối
# Chúng ta cần quote lại chuỗi kết nối để xử lý các ký tự đặc biệt như dấu gạch chéo ngược (\)
params = urllib.parse.quote_plus(
    f'DRIVER={{{DRIVER}}};'
    f'SERVER={SERVER};'
    f'DATABASE={DATABASE};'
    f'Trusted_Connection=yes;'
)

# 2. Khởi tạo Engine
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# 3. Viết câu lệnh SQL lấy dữ liệu
# Thay 'YourTableName' bằng tên bảng thực tế trong toy_store_datawarehouse
query = "SELECT TOP 100 * FROM stage" 

try:
    # 4. Đọc dữ liệu vào DataFrame
    df = pd.read_sql(query, engine)
    
    # Hiển thị kết quả
    print("Kết nối thành công! Dưới đây là dữ liệu:")
    print(df.head())

except Exception as e:
    print(f"Có lỗi xảy ra: {e}")

Kết nối thành công! Dưới đây là dữ liệu:
   website_pageview_id          created_at  website_session_id  \
0               510692 2014-03-17 16:05:47              215123
1               510699 2014-03-17 16:09:47              215123
2               510709 2014-03-17 16:17:00              215123
3               510690 2014-03-17 16:04:06              215123
4               510699 2014-03-17 16:09:47              215123

                pageview_url  user_id  is_repeat_session utm_source  \
0     /the-original-mr-fuzzy   186019                  0    gsearch
1                  /shipping   186019                  0    gsearch
2  /thank-you-for-your-order   186019                  0    gsearch
3                  /products   186019                  0    gsearch
4                  /shipping   186019                  0    gsearch

  utm_campaign utm_content device_type             http_referer  order_id  \
0     nonbrand      g_ad_1      mobile  https://www.gsearch.com     12619
1     nonbrand      g_ad_1      mobile  https://www.gsearch.com     12619
2     nonbrand      g_ad_1      mobile  https://www.gsearch.com     12619
3     nonbrand      g_ad_1      mobile  https://www.gsearch.com     12619
4     nonbrand      g_ad_1      mobile  https://www.gsearch.com     12619

   primary_product_id  items_purchased  price_usd  cogs_usd  order_item_id  \
0                   1                1      49.99     19.49          13429
1                   1                1      49.99     19.49          13429
2                   1                1      49.99     19.49          13429
3                   1                1      49.99     19.49          13429
4                   1                1      49.99     19.49          13429

   product_id  is_primary_item            product_name
0           1                1  The Original Mr. Fuzzy
1           1                1  The Original Mr. Fuzzy
2           1                1  The Original Mr. Fuzzy
3           1                1  The Original Mr. Fuzzy
4           1                1  The Original Mr. Fuzzy

### 1.1. Data Stage

In [5]:
data = pd.read_sql(query, engine)

In [6]:
data.head(10)

,website_pageview_id,created_at,website_session_id,pageview_url,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer,order_id,primary_product_id,items_purchased,price_usd,cogs_usd,order_item_id,product_id,is_primary_item,product_name
0,510692,2014-03-17 16:05:47,215123,/the-original-mr-fuzzy,186019,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,12619,1,1,49.99,19.49,13429,1,1,The Original Mr. Fuzzy
1,510699,2014-03-17 16:09:47,215123,/shipping,186019,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,12619,1,1,49.99,19.49,13429,1,1,The Original Mr. Fuzzy
2,510709,2014-03-17 16:17:00,215123,/thank-you-for-your-order,186019,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,12619,1,1,49.99,19.49,13429,1,1,The Original Mr. Fuzzy
3,510690,2014-03-17 16:04:06,215123,/products,186019,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,12619,1,1,49.99,19.49,13429,1,1,The Original Mr. Fuzzy
4,510699,2014-03-17 16:09:47,215123,/shipping,186019,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,12619,1,1,49.99,19.49,13429,1,1,The Original Mr. Fuzzy
5,510692,2014-03-17 16:05:47,215123,/the-original-mr-fuzzy,186019,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,12619,1,1,49.99,19.49,13429,1,1,The Original Mr. Fuzzy
6,510703,2014-03-17 16:12:36,215123,/billing-2,186019,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,12619,1,1,49.99,19.49,13429,1,1,The Original Mr. Fuzzy
7,510686,2014-03-17 16:01:58,215123,/lander-3,186019,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,12619,1,1,49.99,19.49,13429,1,1,The Original Mr. Fuzzy
8,510690,2014-03-17 16:04:06,215123,/products,186019,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,12619,1,1,49.99,19.49,13429,1,1,The Original Mr. Fuzzy
9,510696,2014-03-17 16:07:54,215123,/cart,186019,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,12619,1,1,49.99,19.49,13429,1,1,The Original Mr. Fuzzy

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   website_pageview_id  100 non-null    int64
 1   created_at           100 non-null    datetime64[ns]
 2   website_session_id   100 non-null    int64
 3   pageview_url         100 non-null    object
 4   user_id              100 non-null    int64
 5   is_repeat_session    100 non-null    int64
 6   utm_source           100 non-null    object
 7   utm_campaign         100 non-null    object
 8   utm_content          100 non-null    object
 9   device_type          100 non-null    object
 10  http_referer         100 non-null    object
 11  order_id             100 non-null    int64
 12  primary_product_id   100 non-null    int64
 13  items_purchased      100 non-null    int64
 14  price_usd            100 non-null    float64
 15  cogs_usd             100 non-null    float64
 16  order_item_id        100 non-null    int64
 17  product_id           100 non-null    int64
 18  is_primary_item      100 non-null    int64
 19  product_name         100 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(10), object(7)
memory usage: 15.8+ KB

In [8]:
data.isnull().sum()

website_pageview_id    0
created_at             0
website_session_id     0
pageview_url           0
user_id                0
is_repeat_session      0
utm_source             0
utm_campaign           0
utm_content            0
device_type            0
http_referer           0
order_id               0
primary_product_id     0
items_purchased        0
price_usd              0
cogs_usd               0
order_item_id          0
product_id             0
is_primary_item        0
product_name           0
dtype: int64

In [9]:
data.duplicated().sum()

47

### 1.2. Save data stage

In [10]:
data.to_csv('data/processed/stage.csv', index=False)
print("Save data to CSV successfully!")

Save data to CSV successfully!

### 1.3. Save data dim order

In [11]:
data_dim_order = pd.read_sql("SELECT * FROM dim_order", engine)

In [12]:
data_dim_order.head(10)

   order_id  user_id  is_repeat_session
0         1       20                  0
1         2      104                  0
2         3      147                  0
3         4      160                  0
4         5      177                  0
5         6      232                  0
6         7      241                  0
7         8      295                  0
8         9      304                  0
9        10      317                  0

In [13]:
data_dim_order.shape

(32313, 3)

In [14]:
data_dim_order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           32313 non-null  int64
 1   user_id            32313 non-null  int64
 2   is_repeat_session  32313 non-null  int64
dtypes: int64(3)
memory usage: 757.5 KB

In [15]:
data_dim_order.isnull().sum()

order_id             0
user_id              0
is_repeat_session    0
dtype: int64

In [17]:
data_dim_order.duplicated().sum()

0

In [18]:
# save data_dim_order to csv
data_dim_order.to_csv('data/processed/dim_order.csv', index=False)

### 1.4. Save data dim papeview

In [22]:
data_dim_papeview = pd.read_sql("select * from dim_papeview", engine)

In [23]:
data_dim_papeview.head(10)

   website_pageview_id               pageview_url
0                   30                      /home
1                   32                  /products
2                   33     /the-original-mr-fuzzy
3                   34                      /cart
4                   35                  /shipping
5                   36                   /billing
6                   37  /thank-you-for-your-order
7                  178                      /home
8                  179                  /products
9                  180     /the-original-mr-fuzzy

In [24]:
data_dim_papeview.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226191 entries, 0 to 226190
Data columns (total 2 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   website_pageview_id  226191 non-null  int64
 1   pageview_url         226191 non-null  object
dtypes: int64(1), object(1)
memory usage: 3.5+ MB

In [25]:
data_dim_papeview.isnull().sum()

website_pageview_id    0
pageview_url           0
dtype: int64

In [26]:
data_dim_papeview.duplicated().sum()

0

In [28]:
data_dim_papeview.to_csv('data/processed/dim_papeview.csv', index=False)
print("Save data_dim_papeview to CSV successfully!")

Save data_dim_papeview to CSV successfully!

### 1.5. Save data dim product

In [29]:
data_dim_product = pd.read_sql("select * from dim_product", engine)

In [30]:
data_dim_product.head(10)

   product_id                product_name
0           1      The Original Mr. Fuzzy
1           2       The Forever Love Bear
2           3    The Birthday Sugar Panda
3           4  The Hudson River Mini bear

In [31]:
data_dim_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    4 non-null      int64
 1   product_name  4 non-null      object
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [32]:
data_dim_product.to_csv('data/processed/dim_product.csv', index=False)
print("Save data_dim_product to CSV successfully!")

Save data_dim_product to CSV successfully!

### 1.6. Save data dim session

In [33]:
data_dim_session = pd.read_sql("select * from dim_session", engine)

In [34]:
data_dim_session.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   website_session_id  32313 non-null  int64
 1   utm_source          32313 non-null  object
 2   utm_campaign        32313 non-null  object
 3   utm_content         32313 non-null  object
 4   device_type         32313 non-null  object
 5   http_referer        32313 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.5+ MB

In [35]:
data_dim_session.isnull().sum()

website_session_id    0
utm_source            0
utm_campaign          0
utm_content           0
device_type           0
http_referer          0
dtype: int64

In [36]:
data_dim_session.duplicated().sum()

0

In [37]:
data_dim_session.to_csv('data/processed/dim_session.csv', index=False)
print("Save data_dim_session to CSV successfully!")

Save data_dim_session to CSV successfully!

### 1.7. Save dat dim time table

In [38]:
data_dim_time = pd.read_sql("select * from dim_time", engine)

In [39]:
data_dim_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225504 entries, 0 to 225503
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   created_at  225504 non-null  datetime64[ns]
 1   year        225504 non-null  int64
 2   month       225504 non-null  int64
 3   day         225504 non-null  int64
 4   time_id     225504 non-null  int64
dtypes: datetime64[ns](1), int64(4)
memory usage: 8.6 MB

In [43]:
data_dim_time.isnull().sum()

created_at    0
year          0
month         0
day           0
time_id       0
dtype: int64

In [44]:
data_dim_time.duplicated().sum()

0

In [45]:
data_dim_time.to_csv('data/processed/dim_time.csv', index=False)
print("Save data_dim_time to CSV successfully!")

Save data_dim_time to CSV successfully!