In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
fact = pd.read_csv("data/processed/fact.csv")
dim_session = pd.read_csv("data/processed/dim_session.csv")
dim_product = pd.read_csv("data/processed/dim_product.csv")
dim_order = pd.read_csv("data/processed/dim_order.csv")
dim_time = pd.read_csv("data/processed/dim_time.csv")

## 1. Join tables

### 1.1. Join dim_session

In [3]:
df = fact.merge(
    dim_session,
    on="website_session_id",
    how="left"
)

### 1.2. Join dim_session

In [4]:
df = df.merge(
    dim_product,
    on="product_id",
    how="left"
)

In [5]:
df.head(10)

,website_pageview_id,website_session_id,order_id,items_purchased,price_usd,cogs_usd,order_item_id,product_id,is_primary_item,time_id,row_id,user_id,utm_source,utm_campaign,utm_content,device_type,http_referer,product_name
0,641082,266012,16329,4,151.96,47.96,18452,4,0,94544,1,227499,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com,The Hudson River Mini bear
1,1082854,434473,29042,4,191.96,67.96,35697,1,0,185712,2,364062,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com,The Original Mr. Fuzzy
2,903485,367446,23641,2,99.98,38.98,28398,1,1,81316,3,309885,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com,The Original Mr. Fuzzy
3,292828,126056,6840,2,119.98,44.98,6840,2,1,99345,4,110369,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com,The Forever Love Bear
4,1010319,407785,26828,2,59.98,18.98,32693,4,1,151109,5,323819,NaN,NaN,NaN,desktop,https://www.gsearch.com,The Hudson River Mini bear
5,1036701,417624,27600,2,99.98,38.98,33723,1,1,189630,6,351230,NaN,NaN,NaN,desktop,https://www.gsearch.com,The Original Mr. Fuzzy
6,837831,342201,21732,2,99.98,38.98,25795,1,1,952,7,289337,bsearch,nonbrand,b_ad_1,desktop,https://www.bsearch.com,The Original Mr. Fuzzy
7,126810,58229,2376,2,99.98,38.98,2376,1,1,151059,8,53074,bsearch,nonbrand,b_ad_1,desktop,https://www.bsearch.com,The Original Mr. Fuzzy
8,894299,363906,23379,4,159.96,57.96,28040,1,1,180115,9,306970,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com,The Original Mr. Fuzzy
9,1117864,447125,30191,2,99.98,38.98,37175,1,1,64082,10,374089,bsearch,nonbrand,b_ad_1,desktop,https://www.bsearch.com,The Original Mr. Fuzzy

In [6]:
df.shape

(280175, 18)

### 1.3. Join dim_order

In [7]:
df = df.merge(
    dim_order,
    on="order_id",
    how="left"
)

In [8]:
df.shape

(280175, 20)

### 1.4. Join dim_time

In [9]:
df = df.merge(
    dim_time,
    on="time_id",
    how="left"
)

## 2. Data after join

In [10]:
df.head(10)

,website_pageview_id,website_session_id,order_id,items_purchased,price_usd,cogs_usd,order_item_id,product_id,is_primary_item,time_id,...,http_referer,product_name,primary_product_id,is_repeat_session,created_at,year,month,day,quater,hour
0,641082,266012,16329,4,151.96,47.96,18452,4,0,94544,...,https://www.gsearch.com,The Hudson River Mini bear,3,0,2014-06-16 05:36:08,2014,6,16,2,5
1,1082854,434473,29042,4,191.96,67.96,35697,1,0,185712,...,https://www.gsearch.com,The Original Mr. Fuzzy,3,0,2015-02-02 02:13:38,2015,2,2,1,2
2,903485,367446,23641,2,99.98,38.98,28398,1,1,81316,...,https://www.gsearch.com,The Original Mr. Fuzzy,1,0,2014-11-19 15:43:04,2014,11,19,4,15
3,292828,126056,6840,2,119.98,44.98,6840,2,1,99345,...,https://www.gsearch.com,The Forever Love Bear,2,0,2013-09-04 09:42:12,2013,9,4,3,9
4,1010319,407785,26828,2,59.98,18.98,32693,4,1,151109,...,https://www.gsearch.com,The Hudson River Mini bear,4,1,2014-12-31 02:33:30,2014,12,31,4,2
5,1036701,417624,27600,2,99.98,38.98,33723,1,1,189630,...,https://www.gsearch.com,The Original Mr. Fuzzy,1,0,2015-01-12 11:26:26,2015,1,12,1,11
6,837831,342201,21732,2,99.98,38.98,25795,1,1,952,...,https://www.bsearch.com,The Original Mr. Fuzzy,1,0,2014-10-15 15:14:40,2014,10,15,4,15
7,126810,58229,2376,2,99.98,38.98,2376,1,1,151059,...,https://www.bsearch.com,The Original Mr. Fuzzy,1,0,2012-12-17 15:33:23,2012,12,17,4,15
8,894299,363906,23379,4,159.96,57.96,28040,1,1,180115,...,https://www.gsearch.com,The Original Mr. Fuzzy,1,0,2014-11-14 17:14:53,2014,11,14,4,17
9,1117864,447125,30191,2,99.98,38.98,37175,1,1,64082,...,https://www.bsearch.com,The Original Mr. Fuzzy,1,0,2015-02-16 10:41:10,2015,2,16,1,10

In [11]:
df.shape

(280175, 26)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280175 entries, 0 to 280174
Data columns (total 26 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   website_pageview_id  280175 non-null  int64
 1   website_session_id   280175 non-null  int64
 2   order_id             280175 non-null  int64
 3   items_purchased      280175 non-null  int64
 4   price_usd            280175 non-null  float64
 5   cogs_usd             280175 non-null  float64
 6   order_item_id        280175 non-null  int64
 7   product_id           280175 non-null  int64
 8   is_primary_item      280175 non-null  int64
 9   time_id              280175 non-null  int64
 10  row_id               280175 non-null  int64
 11  user_id              280175 non-null  int64
 12  utm_source           226296 non-null  object
 13  utm_campaign         226296 non-null  object
 14  utm_content          226296 non-null  object
 15  device_type          280175 non-null  object
 16  http_referer         254863 non-null  object
 17  product_name         280175 non-null  object
 18  primary_product_id   280175 non-null  int64
 19  is_repeat_session    280175 non-null  int64
 20  created_at           280175 non-null  object
 21  year                 280175 non-null  int64
 22  month                280175 non-null  int64
 23  day                  280175 non-null  int64
 24  quater               280175 non-null  int64
 25  hour                 280175 non-null  int64
dtypes: float64(2), int64(17), object(7)
memory usage: 55.6+ MB

In [13]:
df.isnull().sum()

website_pageview_id        0
website_session_id         0
order_id                   0
items_purchased            0
price_usd                  0
cogs_usd                   0
order_item_id              0
product_id                 0
is_primary_item            0
time_id                    0
row_id                     0
user_id                    0
utm_source             53879
utm_campaign           53879
utm_content            53879
device_type                0
http_referer           25312
product_name               0
primary_product_id         0
is_repeat_session          0
created_at                 0
year                       0
month                      0
day                        0
quater                     0
hour                       0
dtype: int64

In [14]:
df.duplicated().sum()

0

In [15]:
df['is_repeat_session'].value_counts()

is_repeat_session
0    226156
1     54019
Name: count, dtype: int64

In [16]:
df.columns

Index(['website_pageview_id', 'website_session_id', 'order_id',
       'items_purchased', 'price_usd', 'cogs_usd', 'order_item_id',
       'product_id', 'is_primary_item', 'time_id', 'row_id', 'user_id',
       'utm_source', 'utm_campaign', 'utm_content', 'device_type',
       'http_referer', 'product_name', 'primary_product_id',
       'is_repeat_session', 'created_at', 'year', 'month', 'day', 'quater',
       'hour'],
      dtype='object')

## 3. Feature Engineering

### 3.1. Tính Revenue theo Session